apiVersion: v1
kind: ConfigMap
metadata:
  name: peer0-org1-cm
  namespace: org1 
data:
  CORE_PEER_ID: "peer0-org1.org1.svc.cluster.local"
  CORE_PEER_NETWORKID: dev 
  CORE_PEER_ADDRESS: "peer0-org1.org1.svc.cluster.local:7051"
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODEADDRESS: "peer0-org1.org1.svc.cluster.local:7052"
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: "peer0-org1.org1.svc.cluster.local:7051"
  CORE_PEER_LOCALMSPID: "Org1MSP"
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  FABRIC_LOGGING_SPEC: "INFO"
  CORE_PEER_TLS_ENABLED: "true" 
  CORE_PEER_GOSSIP_USELEADERELECTION: "true" 
  CORE_PEER_GOSSIP_ORGLEADER: "false"  # 设置为true，静态选举，默认一个节点
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_MSPCONFIGPATH: "/etc/hyperledger/fabric/peer/msp"
  CORE_PEER_TLS_CERT_FILE: "/etc/hyperledger/fabric/tls/pair/tls.crt"
  CORE_PEER_TLS_KEY_FILE: "/etc/hyperledger/fabric/tls/pair/tls.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "/etc/hyperledger/fabric/tls/ca.crt" 