apiVersion: v1
kind: ConfigMap
metadata:
  name: org1-client-cm
  namespace: org1 
data:
  GOPATH: "/opt/gopath"
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  FABRIC_LOGGING_SPEC: "INFO"
  CORE_PEER_ID: "org1-cli"
  CORE_PEER_ADDRESS: "peer0-org1.org1.svc.cluster.local:7051"
  CORE_PEER_LOCALMSPID: "Org1MSP"
  CORE_PEER_TLS_ENABLED: "true" 
  CORE_PEER_TLS_CERT_FILE: "/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/pair/tls.crt"
  CORE_PEER_TLS_KEY_FILE: "/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/pair/tls.key" 
  CORE_PEER_TLS_ROOTCERT_FILE: "/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/ca.crt" 
  CORE_PEER_MSPCONFIGPATH: "/opt/gopath/src/github.com/hyperledger/fabric/peer/admin/msp" 
  CA_FILE: "/opt/gopath/src/github.com/hyperledger/fabric/peer/tlsca-orderer-cert.pem" 
