version: '2'

services:
  fabric-rootca-server:
    image: hyperledger/fabric-ca:1.4.1
    container_name: fabric-rootca-server
    command: fabric-ca-server start -b admin:adminpw
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=fabric-rootca-server
      - FABRIC_CA_SERVER_CFG_AFFILIATIONS_ALLOWREMOVE=true  # 允许删除联盟关系
      - FABRIC_CA_SERVER_CFG_IDENTITIES_ALLOWREMOVE=true  # 允许删除成员身份
    ports:
      - 7055:7054

  fabric-imdca-server:
    image: hyperledger/fabric-ca:1.4.1
    container_name: fabric-imdca-server
    command: sh -c 'sleep 3; fabric-ca-server start -b admin:12345 -u http://admin:adminpw@fabric-rootca-server:7054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-imdca-server
      - FABRIC_CA_SERVER_CA_NAME=fabric-imdca-server
      - FABRIC_CA_SERVER_CFG_AFFILIATIONS_ALLOWREMOVE=true  # 允许删除联盟关系
      - FABRIC_CA_SERVER_CFG_IDENTITIES_ALLOWREMOVE=true  # 允许删除成员身份
    ports:
      - 7056:7054
    depends_on:
      - fabric-rootca-server
